version: 2.20.2.{build}
environment:
    PROJECT_NAME:  'Cube.Pdf'
    PROJECT_BIN:   'bin\%PLATFORM%\%CONFIGURATION%\net45'
    TEST_TOOL:     '..\packages\OpenCover\4.7.922\tools\OpenCover.Console.exe'
    TEST_ARGS:     'test --no-restore --no-build --logger:Appveyor'
    TEST_FILTERS:  '+[Cube*]* -[*]*.NativeMethods -[*]*.Properties.* -[*]*.Program -[*]*.App -[*]*Window -[*]*Control'
    TEST_COVERAGE: 'CoverResults.xml'
    TEST_RESULTS:  'TestResults'
clone_folder: 'C:\Cube\%PROJECT_NAME%'
image: Visual Studio 2019
platform: Any CPU
configuration: Release
skip_tags: true
branches:
    only:
        - master
nuget:
    project_feed: true
    disable_publish_on_pr: true
before_build:
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget sources add -name Cube.FileSystem -source https://ci.appveyor.com/nuget/cube.filesystem
    - nuget sources add -name Cube.Xui -source https://ci.appveyor.com/nuget/cube.xui
    - nuget sources add -name Cube.Images -source https://ci.appveyor.com/nuget/cube.images
    - nuget sources add -name Cube.Forms -source https://ci.appveyor.com/nuget/cube.forms
    - nuget restore "%PROJECT_NAME%.sln"
build:
    project: '%PROJECT_NAME%.sln'
    parallel: true
    publish_nuget: true
    verbosity: minimal
test_script:
    - >
      "%TEST_TOOL%"
      -log:Error
      -register:appveyor
      -target:dotnet.exe
      -targetargs:"%TEST_ARGS% %PROJECT_NAME%.sln"
      -returntargetcode
      -hideskipped:All
      -mergeoutput
      -output:"%TEST_COVERAGE%"
      -filter:"%TEST_FILTERS%"
after_test:
    - pip install codecov
    - codecov -f "%TEST_COVERAGE%"
    - xcopy /q /Y /I "Applications\Converter\Proxy\%PROJECT_BIN%" CubePdf
    - xcopy /q /Y /I "Applications\Converter\Main\%PROJECT_BIN%" CubePdf
    - xcopy /q /Y /I "Applications\Editor\Proxy\%PROJECT_BIN%" CubePdf.Utility
    - xcopy /q /Y /I "Applications\Editor\Main\%PROJECT_BIN%" CubePdf.Utility
    - xcopy /q /Y /I "Tests\Core\%PROJECT_BIN%\*.log" "%TEST_RESULTS%\"
    - xcopy /q /Y /I "Tests\Converter\%PROJECT_BIN%\*.log" "%TEST_RESULTS%\"
    - xcopy /q /Y /I "Tests\Editor\%PROJECT_BIN%\*.log" "%TEST_RESULTS%\"
    - xcopy /q /Y /I "Tests\Pages\%PROJECT_BIN%\*.log" "%TEST_RESULTS%\"
    - xcopy /q /Y /I "Tests\Clip\%PROJECT_BIN%\*.log" "%TEST_RESULTS%\"
    - xcopy /q /Y /I "Tests\Picker\%PROJECT_BIN%\*.log" "%TEST_RESULTS%\"
    - xcopy /q /Y /I "%TEST_COVERAGE%" "%TEST_RESULTS%\"
artifacts:
    - path: 'CubePdf'
    - path: 'CubePdf.Utility'
    - path: '%TEST_RESULTS%'
