version: 2.16.0.{build}
image: Visual Studio 2019 Preview
platform: Any CPU
configuration: Release
environment:
    PROJECT_NAME:   'Cube.Pdf'
    PROJECT_BIN:    'bin\%PLATFORM%\%CONFIGURATION%\net45'
    PROJECT_LIB:    '..\packages'
    TEST_TOOL:      '$(PROJECT_LIB)\OpenCover\4.7.922\tools\OpenCover.Console.exe'
    TEST_CORETOOL:  'nunit3-console.exe'
    TEST_FILTERS:   '+[Cube*]* -[*]*.NativeMethods -[*]*.Properties.* -[*]*.Program -[*]*.App -[*]*Window -[*]*Control'
    TEST_RESULT:    'TestResult.xml'
    TEST_COVERAGE:  'CoverResults.xml'
    TEST_LOG:       'TestResults'
branches:
    only:
        - master
skip_tags: true
nuget:
    project_feed: true
    disable_publish_on_pr: true
clone_folder: 'C:\Cube\%PROJECT_NAME%'
before_build:
    - nuget restore "%PROJECT_NAME%.Apps.sln"
build:
    project: '%PROJECT_NAME%.Apps.sln'
    parallel: true
    publish_nuget: true
    verbosity: minimal
after_build:
    - rake copy
test_script:
    - >
      "%TEST_TOOL%"
      -log:Error
      -register:user
      -target:"%TEST_CORETOOL%"
      -targetargs:"%PROJECT_NAME%.Tests.dll"
      -targetdir:"Libraries\Tests\%PROJECT_BIN%"
      -returntargetcode
      -hideskipped:All
      -output:"%TEST_COVERAGE%"
      -filter:"%TEST_FILTERS%"
    - >
      "%TEST_TOOL%"
      -log:Error
      -register:user
      -target:"%TEST_CORETOOL%"
      -targetargs:"%PROJECT_NAME%.Converter.Tests.dll"
      -targetdir:"Applications\Converter\Tests\%PROJECT_BIN%"
      -returntargetcode
      -hideskipped:All
      -mergeoutput
      -output:"%TEST_COVERAGE%"
      -filter:"%TEST_FILTERS%"
    - >
      "%TEST_TOOL%"
      -log:Error
      -register:user
      -target:"%TEST_CORETOOL%"
      -targetargs:"%PROJECT_NAME%.Editor.Tests.dll"
      -targetdir:"Applications\Editor\Tests\%PROJECT_BIN%"
      -returntargetcode
      -hideskipped:All
      -mergeoutput
      -output:"%TEST_COVERAGE%"
      -filter:"%TEST_FILTERS%"
after_test:
    - xcopy /q /Y /I "Applications\Converter\Proxy\%PROJECT_BIN%" CubePdf
    - xcopy /q /Y /I "Applications\Converter\Main\%PROJECT_BIN%" CubePdf
    - xcopy /q /Y /I "Applications\Editor\Proxy\%PROJECT_BIN%" CubePdf.Utility
    - xcopy /q /Y /I "Applications\Editor\Main\%PROJECT_BIN%" CubePdf.Utility
    - xcopy /q /Y /I "Libraries\Tests\%PROJECT_BIN%\*.log" "%TEST_LOG%\"
    - xcopy /q /Y /I "Applications\Converter\Tests\%PROJECT_BIN%\*.log" "%TEST_LOG%\"
    - xcopy /q /Y /I "Applications\Editor\Tests\%PROJECT_BIN%\*.log" "%TEST_LOG%\"
    - xcopy /q /Y /I "%TEST_COVERAGE%" "%TEST_LOG%\"
artifacts:
    - path: 'CubePdf'
    - path: 'CubePdf.Utility'
    - path: '%TEST_LOG%'
